function[] = test2Num()
% Projekt 1, zadanie 01, test 2 numeryczny
% Vlada Gromova, 323770

text = "Sprawdzenie działania programu dla równań wyższych rzędów. \n\n";
fprintf(text);
fprintf("Równanie 2-go rzędu:\n");
fprintf("Problem: (x^2)*y"" - 2*x*y' + 2*y = 6, y(1) = 5, y'(1) =" + ...
    " 3. y(2)-?\nDokładne rozwiązanie: y(x) = x^2 + x + 3. y(2) = 9.\n\n");
[resAM,resEul] = P1Z01_VGR_rozniczk(1,2,500,[5;3],50,@(x) x^2, ...
    @(x) -2*x,@(x) 2,@(x) 6);
fprintf("Wartość y(2) obliczona zmodyfikowaną metodą Eulera: " + ...
    "%d \n",resEul(501));
fprintf("Wartość y(2) obliczona metodą Adamsa-Moultona: %d \n",resAM(501));
fprintf("Bląd metody Eulera: %d \n",abs(9 - resEul(501)));
fprintf("Bląd metody Adamsa-Moultona: %d \n\n",abs(9 - resAM(501)));
pause;

fprintf("Równanie 3-go rzędu:\n");
fprintf("Problem: y^{3} - y' = 0, y(2) = 1, y'(2) = 0, y''(2) = -1." + ...
    " y(5)-?\nDokładne rozwiązanie: y(x) = -exp(x-2)/2 - exp(2-x)/2" + ...
    " + 2. y(5) ~ -8.06766199578.\n\n");
[resAM,resEul] = P1Z01_VGR_rozniczk(2,5,500,[1;0;-1],50,@(x) 1,@(x) 0, ...
    @(x) -1,@(x) 0,@(x) 0);
fprintf("Wartość y(5) obliczona zmodyfikowaną metodą Eulera: " + ...
    "%d \n",resEul(501));
fprintf("Wartość y(5) obliczona metodą Adamsa-Moultona: %d \n",resAM(501));
fprintf("Bląd metody Eulera: %d \n",abs(-exp(3)/2-exp(-3)/2+2 ...
    -resEul(501)));
fprintf("Bląd metody Adamsa-Moultona: %d \n\n",abs(-exp(3)/2- ...
    exp(-3)/2+2-resAM(501)));
pause;

fprintf("Równanie 4-go rzędu:\n");
fprintf("Problem: y^{4} = cos(x) - sin(x), y(0) = 0, y'(0) = " + ...
    "y""(0) = -1, y^{3}(0) = 7. y(3)-?\nDokładne rozwiązanie: " + ...
    "y(x) = - sin(x) + cos(x) + x^3 - 1. y(3) ~ 24.8688874953\n\n");
[resAM,resEul] = P1Z01_VGR_rozniczk(0,3,2345,[0;-1;-1;7],50, ...
    @(x) 1,@(x) 0,@(x) 0,@(x) 0,@(x) 0,@(x) - sin(x) + cos(x));
fprintf("Wartość y(3) obliczona zmodyfikowaną metodą Eulera: " + ...
    "%d \n",resEul(2346));
fprintf("Wartość y(3) obliczona metodą Adamsa-Moultona: %d \n", ...
    resAM(2346));
fprintf("Bląd metody Eulera: %d \n",abs(-sin(3)+cos(3)+3^3-1 ...
    -resEul(2346)));
fprintf("Bląd metody Adamsa-Moultona: %d \n\n",abs(-sin(3)+cos(3)+3^3 ...
    -1-resAM(2346)));

